OpenAI functions
DataSQRL/sqrl-functions pull request #13
Opened 2024-10-30 13:55 UTC by nandorsoma

2024-11-01 18:17 UTC, mbroecheler requested changes
The core API calls look good. See comments on changes.

2024-11-01 18:17 UTC, mbroecheler commented on sqrl-openai/pom.xml
> +        <dependency>
Flink shades jackson. Take a look at the sqrl-json library for an example of how to use the shaded library
by used provided dependencies:
https://github.com/DataSQRL/sqrl/tree/main/sqrl-flink-lib/sqrl-json

In general, we want to minimize the dependencies we pull in that are not provided.

2024-11-01 18:17 UTC, mbroecheler commented on sqrl-openai/src/main/java/com/datasqrl/openai/completions.java
> +    public String eval(String prompt, String modelName, Integer maxOutputTokens, Double temperature, Double topP, int maxRetries) {
probably irrelevant now since we'll move to Async functions eventually.

2024-11-01 18:17 UTC, mbroecheler commented on sqrl-openai/src/test/java/com/datasqrl/openai/ExtractJsonFlinkSqlTest.java
> +package com.datasqrl.openai;
This does not add any additional test coverage. Please remove.

2024-11-01 18:17 UTC, mbroecheler commented on sqrl-openai/src/test/java/com/datasqrl/openai/CompletionsFlinkSqlTest.java
> +package com.datasqrl.openai;
This does not add any additional test coverage. Please remove.

2024-11-01 18:17 UTC, mbroecheler commented on sqrl-openai/src/main/java/com/datasqrl/openai/completions.java
> +    public String eval(String prompt, String modelName, Integer maxOutputTokens, Double temperature, Double topP, int maxRetries) {
please remove from docs as well.

2024-11-06 09:20 UTC, nandorsoma commented
Thanks for the review @mbroecheler! I addressed your comments. Can you take a look at it one more time?

2024-11-06 17:09 UTC, mbroecheler commented on sqrl-openai/README.md
> +        re
what is re? Can you use full names instead of 2 letter abbreviations?

2024-11-06 17:09 UTC, mbroecheler commented on sqrl-openai/sqrl-package/README.md
> +    completions(prompt, 'gpt-4o') AS re,
Same here

2024-11-06 17:10 UTC, mbroecheler commented on sqrl-openai/src/main/java/com/datasqrl/openai/RetryUtil.java
> +                .orElse(3);
make this a static variable `MAX_RETRIES_DEFAULT` so one doesn't have to look around the code to find the default value.

2024-11-07 11:06 UTC, nandorsoma commented
Thank you @mbroecheler, I addressed your comments. Merging now.

2024-11-07 11:06 UTC, merged