Vector embedding using pytorch
DataSQRL/sqrl-functions pull request #20
Opened 2024-11-23 00:40 UTC by nandorsoma

2024-11-23 19:58 UTC, mbroecheler requested changes
See comments. The direction looks good. Can you also add a function for sentiment analysis based on the flink example of dlj that's linked in the doc?

2024-11-23 19:58 UTC, mbroecheler commented on sqrl-pytorch/pom.xml
> +        <dependency>
Can you use the one that comes with Flink?

2024-11-23 19:58 UTC, mbroecheler commented on sqrl-pytorch/snapshots-pytorch-cicd-test/results.snapshot
> +{"data":{"results":[{"vector_embedd_result":"[0.6445954, 0.23840412, -0.4179771, 0.12996641, -0.38940284, 0.36838385, -0.16495298, -0.11583278, -0.08997916]"}]}}
The vector only has 9 entries? That doesn't seem quite right.

2024-11-23 19:58 UTC, mbroecheler commented on sqrl-pytorch/src/main/java/com/datasqrl/pytorch/EmbeddingsService.java
> +    private ZooModel<String, float[]> model = null;
Should this be a hashmap keyed by model name so users can use different embedding models in the same SQRL script. Right now, it'll use the first model and ignore all others.

2024-11-23 19:58 UTC, mbroecheler commented on sqrl-pytorch/pytorch-cicd-test.sqrl
> +data := SELECT * FROM (VALUES
I think we have to use data from a file to work around the current limitation of it trying to reduce static function calls. Or does this work now?

2025-06-15 22:41 UTC, nandorsoma commented
Feel free to reopen if needed.

2025-06-15 22:41 UTC, closed without merging